Task_1_1_1
FortrainMas/OOP pull request #18
Opened 2024-09-10 09:09 UTC by FortrainMas

2024-09-10 15:39 UTC, FortrainMas commented
![image](https://github.com/user-attachments/assets/adf230b8-84c2-4ab7-a6eb-e73c7d43e403)
На всякий случай, ещё раз асимптотика

2024-09-16 11:16 UTC, shadrina requested changes
* Нет скрипта для сборки без gradle. См. условие задачи.
* Ругается reviewdog. На паре несколько раз рассказывала, что это необходимо проверять перед запросом ревью и объясняла как это проверить: вкладка Files changed

2024-09-18 11:21 UTC, shadrina commented
Доделай, я зачту.

2024-09-23 10:58 UTC, shadrina approved these changes

2024-10-01 08:52 UTC, merged