Task_1_1_2
FortrainMas/OOP pull request #20
Opened 2024-09-11 09:03 UTC by FortrainMas

2024-09-18 11:21 UTC, shadrina requested changes

2024-09-18 11:21 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Blackjack.java
> +    private static DealerHand dealerHand;
Если ты хочешь синглтон, сделай синглон по [паттерну](https://en.wikipedia.org/wiki/Singleton_pattern). Класс с полностью статическим состоянием имеет смысл только тогда, когда он как утилита, а все его поля - не только статические, но и финальные.
В данном случае у тебя обычное изменяемое состояние, я не вижу причин все делать static.

2024-09-18 11:21 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Blackjack.java
> +            userHand.add_card(newCard);
Мы в Java, у нас все названия в camelCase

2024-09-18 11:21 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Blackjack.java
> +                || userScore > 21) {
Я вижу волшебную константу 21 уже, как минимум, третий раз. Напрашивается вынестись в константу.

2024-09-18 11:21 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Blackjack.java
> +                || userScore > 21) {
Волшебные числа по коду вообще рационально выносить в константы с читаемым именем. Если она изменится, не надо будет выискивать все места использования.

2024-09-18 11:21 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Blackjack.java
> +    private static DealerHand dealerHand;
Наличие нестатического состояния не мешает классу иметь статическую точку входа main. Если вдруг загвоздка была в этом. У любого класса можно дорисовать main

2024-09-18 11:21 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Deck.java
> +        }
Я не против. Но в ОО подходе это, конечно, прекрасно бы легло на классы. В данном случае пригодились бы enum'ы.

2024-09-18 11:21 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Hand.java
> +            if (card.weight != 11) {
Да, все-таки весь код в волшебных константах.

2024-09-18 11:21 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Card.java
> +    int weight;
См. инкапсуляция, модификаторы доступа, изменяемость значения, модификатор final.

2024-09-20 06:41 UTC, FortrainMas commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Deck.java
> +        }
Извините, так это необходимо исправить или только учесть на будущее?

2024-09-20 06:46 UTC, FortrainMas commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Blackjack.java
> +    private static DealerHand dealerHand;
В моей реализации действительно дело в статическом main.  Я не могу использовать эти переменные из статического контекста, если они сами не являются статическими, при этом они используются в нескольких различных функциях, из-за чего они не могут быть локальными. Таким образом я хочу реализовать класс, который предполагает только статическое взаимодействие без создания экземпляра. Является ли это допустимой практикой или для таких целей лучше действительно использовать синглтон?

2024-09-23 11:29 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Deck.java
> +        }
В этой лабе попробуй сделать enum'ы. Раз уж опыта такого нет, надо его приобрести.

2024-09-23 11:29 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Blackjack.java
> +    private static DealerHand dealerHand;
Подойдешь на паре, разберемся.

2024-09-23 11:32 UTC, shadrina requested changes

2024-09-23 11:32 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Blackjack.java
> +package ru.nsu.shebanov;
По поводу подбора имени пакета расскажу на паре.

2024-09-23 11:32 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Hand.java
> +        for (Card card : this.cards) {
Я вижу повторяющийся код в этом методе и методе ниже. Может, вынести общую часть?

2024-09-23 11:33 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/Blackjack.java
> +    private static DealerHand dealerHand;
А на вопрос про допустимость практики я ответила выше:

> Класс с полностью статическим состоянием имеет смысл только тогда, когда он как утилита, а все его поля - не только статические, но и финальные.

В других ситуациях обычно причина в неудачном дизайне.

2024-09-24 12:05 UTC, shadrina requested changes
Править можно сегодня-завтра, так как не успела посмотреть на паре. Правки в целом не критичные, но поправить надо.

2024-09-24 12:05 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/Blackjack.java
> +    boolean playerTurn() {
Заботиться об области видимости нужно для любых членов класса: и для полей, и для методов.

2024-09-24 12:05 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/Card.java
> +    int weight;
Сделай [record class](https://docs.oracle.com/en/java/javase/17/language/records.html).

2024-09-24 12:05 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/Deck.java
> +        Suit[] suits = new Suit[] {Suit.CLUBS, Suit.DIAMONDS, Suit.HEARTS, Suit.SPADES};
Для enum'ов такое доступно из коробки, статический метод называется `values()`

2024-09-24 12:05 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/Hand.java
> +    public void add_card(Card card) {
camelCase please

2024-09-24 12:05 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/Rank.java
> +    final String cardName;
Забыл видимость?

2024-09-24 12:05 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/UserHand.java
> +    public String toString() {
Класс отличается именно определением `toString()`, верно?

2024-09-24 12:06 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/Card.java
> +    int weight;
А, наверно не получится, у тебя же тут вес изменяемый.

2024-09-25 04:05 UTC, FortrainMas commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/UserHand.java
> +    public String toString() {
Да, так и есть. Dealer и User hand нужны для различного подхода к выводу. DealerHand также сохраняет состояние открытости или закрытости дополнительной карты.

2024-10-01 08:28 UTC, shadrina reviewed
Доделай

2024-10-01 08:28 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/Blackjack.java
> +    private final int dealerStopScore = 17;
`public static final int BLACKJACK_SCORE = 21;`

2024-10-01 08:28 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/Suit.java
> +    Suit(String suitName) {
Аналогично

2024-10-01 08:28 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/shebanov/blackjack/UserHand.java
> +    UserHand(Card card1, Card card2) {
Модификатор доступа?

2024-10-01 08:50 UTC, shadrina approved these changes

2024-10-01 08:51 UTC, merged